apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: ai-store
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    secretKeyRef:
      name: ai-store-host
      key: ai-store-host
  - name: redisPassword
    secretKeyRef:
      name: ai-store-password
      key: ai-store-host
auth:
  secretStore: secrets
