apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azure-open-ai-davinci
spec:
  type: bindings.azure-open-ai
  version: v1
  metadata:
    - name: deployment
      value: davinci
    - name: endpoint
      secretKeyRef:
        name: azure-open-ai-endpoint
        key: azure-open-ai-endpoint
    - name: key
      secretKeyRef:
        name: azure-open-ai-key
        key: azure-open-ai-key
    - name: maxTokens
      value: 64
    - name: temperature
      value: 0.9
    - name: topP
      value: 1.0
auth:
  secretStore: secrets
