apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azure-ai
spec:
  type: bindings.azure-ai
  version: v1
  metadata:
    - name: azure-ai-endpoint
      secretKeyRef:
        name: azure-ai-endpoint
        key: azure-ai-endpoint
    - name: azure-ai-key
      secretKeyRef:
        name: azure-ai-key
        key: azure-ai-key
auth:
  secretStore: secrets
