apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: chat-gpt
spec:
  type: bindings.chat-gpt
  version: v1
  metadata:
    - name: open-api-endpoint
      value: https://api.openai.com
    - name: open-api-key
      secretKeyRef:
        name: open-api-key
        key: open-api-key
auth:
  secretStore: secrets
