apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: chat-gpt
spec:
  type: bindings.chat-gpt
  version: v1
  metadata:
    - name: endpoint
      secretKeyRef:
        name: open-api-endpoint
        key: open-api-endpoint
    - name: key
      secretKeyRef:
        name: open-api-key
        key: open-api-key
auth:
  secretStore: secrets
